### ISSUE TITLE
Appium-AndroidHQ Documentation incorrect resource

### ISSUE THREAD

**Issue by raulovidiu** [saucelabs-sample-test-frameworks/JS-Mocha-WebdriverIO-Appium-Android#2]
I just want to point to a broken link included in the Readme file: https://github.com/saucelabs-sample-test-frameworks/JS-Mocha-WebdriverIO-Appium-Android#appium-androidhq-documentation

The "Appium-AndroidHQ Documentation" link points to http://www.appium-androidhq.org/docs/ but that resource is not valid ("ERR_NAME_NOT_RESOLVED"). 

I'm not sure what the valid resource is, otherwise I would have provided that.

**Comment by ndmanvar** [comment]
Fixed. Thank you for reporting (:
